version: '3.2'

networks:
    fabcar_net:
        external: 
            name: fabcar_net

services:

    ca_org1:
        networks:
            fabcar_net:
                aliases:
                    - ca.org1.example.com
                    - ca_org1
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 2
            placement:
                constraints:
                    - node.hostname == server2
        image: hyperledger/fabric-ca:latest
        hostname: ca.org1.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca_org1
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/193760dec59a9cf7bb39a6787e505004086463164075fed53532a00a59c6a407_sk
        ports:
            - "7054:7054"   
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/193760dec59a9cf7bb39a6787e505004086463164075fed53532a00a59c6a407_sk -b admin:adminpw -d'
        volumes:
            - /home/salva/fabric-samples/hlfnet/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

    cli:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == server2
        image: hyperledger/fabric-tools:latest
        tty: true
        hostname: cli
        environment:
          - SYS_CHANNEL=$SYS_CHANNEL
          - GOPATH=/opt/gopath
          - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
          - FABRIC_LOGGING_SPEC=INFO
          - CORE_PEER_ID=cli
          - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
          - CORE_PEER_LOCALMSPID=Org1MSP
          - CORE_CHAINCODE_KEEPALIVE=10
          - CORE_PEER_TLS_ENABLED=true
          - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
          - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
          - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
          - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
          
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - /home/salva/fabric-samples/chaincode:/opt/gopath/src/github.com/chaincode
           # - /home/salva/fabric-samples/hyperledger/fabric1:/opt/gopath/src/github.com/hyperledger/fabric
            - /home/salva/fabric-samples/hlfnet/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
            - /home/salva/fabric-samples/hlfnet/channel-artifacts:/var/hyperledger/config
            - /home/salva/fabric-samples/bin/:/var/bin
            # - /var/mynetwork/bin/jq:/usr/local/bin/jq
        networks:
            - fabcar_net

    couchdb0_org1:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 2
            placement:
                constraints:
                    - node.hostname == server2
        image: hyperledger/fabric-couchdb:latest
        hostname: couchdb0_org1
        networks:
           - fabcar_net    

    couchdb1_org1:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 2
            placement:
                constraints:
                    - node.hostname == server2
        image: hyperledger/fabric-couchdb:latest
        hostname: couchdb1_org1
        networks:
           - fabcar_net    