version: '3.2'

networks:
    fabcar_net:
        external: 
            name: fabcar_net

services:

    orderer_org1:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 2
            placement:
                constraints:
                    - node.hostname == server1
        image: hyperledger/fabric-orderer:latest
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
        command: orderer
        hostname: orderer.example.com
        environment:
            - ORDERER_GENERAL_LOGLEVEL=debug
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_GENESISMETHOD=file
            #- ORDERER_GENERAL_GENESISFILE=/var/hyperledger/config/genesis.block
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/msp
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/tls/ca.crt]
            - ORDERER_HOME=/var/hyperledger/orderer
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_LEDGERTYPE=ram
            - CONFIGTX_ORDERER_BATCHSIZE_MAXMESSAGECOUNT=10
            - CONFIGTX_ORDERER_BATCHTIMEOUT=2s
            - CONFIGTX_ORDERER_ADDRESSES=[127.0.0.1:7050]
            - ORDERER_TLS_CLIENTAUTHREQUIRED=false
            - ORDERER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@example.com/tls/ca.crt
            - ORDERER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@example.com/tls/client.crt
            - ORDERER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@example.com/tls/client.key
            - ORDERER_HOST=orderer.example.com
            - CONFIGTX_ORDERER_ORDERERTYPE=kafka
            - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
            #- CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka0:9092,kafka1:9092,kafka2:9092,kafka3:9092]
            #- ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
            #- ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
            - ORDERER_KAFKA_VERBOSE=true
            - ORDERER_GENERAL_GENESISPROFILE=SecureKafka
            - ORDERER_ABSOLUTEMAXBYTES=10MB
            - ORDERER_PREFERREDMAXBYTES=512KB
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
        ports:
          - 7050:7050
        volumes:
            - /home/salva/fabric-samples/hlfnet/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
            - /home/salva/fabric-samples/hlfnet/crypto-config/ordererOrganizations/example.com/users:/var/hyperledger/users
            - /home/salva/fabric-samples/hlfnet/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/msp
            - /home/salva/fabric-samples/hlfnet/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/var/hyperledger/tls
            - /home/salva/fabric-samples/hlfnet/channel-artifacts/:/var/hyperledger/config
            #- orderer.example.com:/var/hyperledger/production/orderer
        networks:
          fabcar_net:
            aliases:
                - orderer.example.com